"""Decision candidate boundary.

MILESTONE-057 gave this boundary its first real behavior: a deterministic,
versioned trading-strategy evaluation over real-shaped market bar data,
producing an immutable, persisted, auditable `DecisionCandidate`. MILESTONE-058
added a multi-instrument opportunity scan and deterministic ranking on top of
the unmodified M057 evaluation. MILESTONE-059 adds a risk-gated trade plan
on top of the unmodified M057/M058 outputs: an explicit, versioned risk
policy that can approve or reject a ranked LONG_CANDIDATE. MILESTONE-060
adds deterministic position sizing and a capital-exposure gate on top of
the unmodified M059 output: an explicit, versioned sizing policy that can
approve or reject a concrete position quantity for an already-approved
trade plan. MILESTONE-061 adds deterministic historical validation and
backtesting on top of the unmodified M057-M060 decision logic: a fixed
dataset, explicit execution/outcome assumptions, and immutable per-trade /
aggregate replay evidence. See
MILESTONE_057_TRADING_EVALUATION_SCOPE_AND_DESIGN.md,
MILESTONE_058_TRADING_OPPORTUNITY_SCANNER_SCOPE_AND_DESIGN.md, and
MILESTONE_059_RISK_GATED_TRADE_PLAN_SCOPE_AND_DESIGN.md,
MILESTONE_060_POSITION_SIZING_CAPITAL_EXPOSURE_GATE_SCOPE_AND_DESIGN.md,
MILESTONE_061_HISTORICAL_STRATEGY_VALIDATION_BACKTESTING_V1_SCOPE_AND_DESIGN.md
for the full scope, contracts, and explicit non-profitability disclaimer.
"""

from empirical_platform.decision_candidate.candidate import DecisionCandidate
from empirical_platform.decision_candidate.corporate_action_stress import (
    CorporateActionSemanticsStressResult,
    StressComparison,
    build_corporate_action_semantics_stress,
)
from empirical_platform.decision_candidate.corporate_actions import (
    CorporateAction,
    CorporateActionManifest,
    CorporateActionType,
    SplitAction,
    SymbolChangeAction,
    corporate_action_manifest_hash,
    split_adjustment_factor_at,
    symbol_at,
    volume_adjustment_factor_at,
)
from empirical_platform.decision_candidate.dataset_snapshot import (
    DIVIDEND_TOTAL_RETURN_HANDLING_NOT_EXERCISED,
    CorporateActionSemantics,
    DatasetSnapshotAuthority,
    PriceSemantics,
    SourceFileManifestEntry,
)
from empirical_platform.decision_candidate.dataset_snapshot_repository import (
    CorporateActionRepository,
    CorporateActionSemanticsStressRepository,
    DatasetSnapshotRepository,
)
from empirical_platform.decision_candidate.historical_backtest import (
    COST_MODEL_ID,
    COST_MODEL_VERSION,
    DECISION_CADENCE,
    DEFAULT_COST_MODEL,
    DEFAULT_EXECUTION_ASSUMPTION,
    DEFAULT_OUTCOME_MODEL,
    EXECUTION_ASSUMPTION_ID,
    EXECUTION_ASSUMPTION_VERSION,
    FIXED_TEST_UNIVERSE,
    OUTCOME_MODEL_ID,
    OUTCOME_MODEL_VERSION,
    HistoricalBacktestRun,
    HistoricalBacktestRunStatus,
    HistoricalCostModel,
    HistoricalDataset,
    HistoricalDatasetAuthority,
    HistoricalExecutionAssumption,
    HistoricalInstrumentSeries,
    HistoricalOutcomeModel,
    HistoricalTradeOutcome,
    HistoricalValidationClassification,
    SameBarAmbiguityPolicy,
    build_historical_backtest_run,
    dataset_sha256,
)
from empirical_platform.decision_candidate.historical_backtest_repository import (
    HistoricalBacktestRunRepository,
)
from empirical_platform.decision_candidate.historical_import import (
    RawSourceFile,
    dataset_snapshot_to_historical_dataset,
    derive_split_adjusted_snapshot,
    import_raw_historical_dataset_snapshot,
    parse_source_csv,
    write_dataset_artifact,
)
from empirical_platform.decision_candidate.historical_universe import universe_at
from empirical_platform.decision_candidate.instrument_master import (
    InstrumentId,
    InstrumentMaster,
    InstrumentMasterEntry,
    InstrumentType,
)
from empirical_platform.decision_candidate.market_data import (
    Bar,
    BarInterval,
    Instrument,
    ObservationWindow,
)
from empirical_platform.decision_candidate.market_data_acquisition import (
    FAKE_SOURCE_NAME,
    YAHOO_FINANCE_SOURCE_NAME,
    FakeMarketDataSource,
    MarketDataAcquisitionError,
    MarketDataFetchRequest,
    MarketDataFetchResult,
    MarketDataSource,
    YahooFinanceChartMarketDataSource,
    translate_fetch_result_to_pipeline_csv,
    translate_yahoo_chart_json_to_pipeline_csv,
)
from empirical_platform.decision_candidate.membership import (
    MembershipManifest,
    MembershipRecord,
    MembershipStatus,
    canonical_membership_payload,
    membership_manifest_hash,
)
from empirical_platform.decision_candidate.portfolio_dependence import (
    DEFAULT_DEPENDENCE_ESTIMATION_POLICY,
    FALSE_DIVERSIFICATION_FIREWALL_LIMITATIONS,
    ConcentrationStressResult,
    ConcurrentExposureState,
    DependenceEstimationPolicy,
    DependenceEvidenceClassification,
    PairDependenceStatus,
    PairwiseDependenceEvidence,
    PortfolioDependenceReport,
    build_concurrent_exposure_states,
    build_pairwise_dependence,
    build_portfolio_dependence_report,
)
from empirical_platform.decision_candidate.portfolio_dependence_repository import (
    PortfolioDependenceReportRepository,
)
from empirical_platform.decision_candidate.portfolio_study import (
    DEFAULT_PORTFOLIO_CAPITAL_POLICY,
    CapitalSensitivityLabel,
    CapitalSensitivityView,
    PortfolioAllocationDecision,
    PortfolioAllocationOutcome,
    PortfolioCapitalPolicy,
    PortfolioEquityObservation,
    PortfolioEventKind,
    PortfolioEvidenceReport,
    PortfolioRejectionReason,
    build_portfolio_evidence_report,
)
from empirical_platform.decision_candidate.portfolio_study_repository import (
    PortfolioStudyRepository,
)
from empirical_platform.decision_candidate.position_plan import (
    DEFAULT_SIZING_POLICY,
    SIZING_POLICY_ID,
    SIZING_POLICY_VERSION,
    PositionPlan,
    PositionPlanRejectionReason,
    PositionPlanStatus,
    PositionSizing,
    PositionSizingContext,
    SizingPolicy,
    build_position_plan,
)
from empirical_platform.decision_candidate.position_plan_repository import PositionPlanRepository
from empirical_platform.decision_candidate.ranking import (
    RANKING_MODEL_ID,
    RANKING_MODEL_VERSION,
    compute_ranking_score,
)
from empirical_platform.decision_candidate.repository import DecisionCandidateRepository
from empirical_platform.decision_candidate.robustness_study import (
    REGIME_POLICY_ID,
    REGIME_POLICY_VERSION,
    HistoricalRobustnessStudy,
    RegimeBreakdownEntry,
    RegimeLabel,
    RobustnessDatasetBundle,
    RobustnessDatasetBundleAuthority,
    RobustnessStudyClassification,
    RobustnessStudyStatus,
    RobustnessUniverseAuthority,
    RobustnessWindow,
    RobustnessWindowResult,
    RobustnessWindowSpec,
    WindowExtreme,
    build_robustness_study,
    regime_breakdown,
)
from empirical_platform.decision_candidate.robustness_study_repository import (
    HistoricalRobustnessStudyRepository,
)
from empirical_platform.decision_candidate.scan import (
    ScanEvaluationEntry,
    TradingOpportunityScan,
    build_scan,
    validate_scan_universe,
)
from empirical_platform.decision_candidate.scan_repository import TradingOpportunityScanRepository
from empirical_platform.decision_candidate.statistical_evidence import (
    DEFAULT_BOOTSTRAP_POLICY,
    FALSE_CONFIDENCE_FIREWALL_LIMITATIONS,
    MINIMUM_RESAMPLE_COUNT,
    SUPPORTED_CONFIDENCE_LEVELS,
    BootstrapInterval,
    BootstrapMethod,
    BootstrapPolicy,
    DrawdownPathEvidence,
    SampleUnit,
    SensitivityLabel,
    SensitivityView,
    StatisticalEvidenceClassification,
    StatisticalEvidenceReport,
    build_statistical_evidence_report,
)
from empirical_platform.decision_candidate.statistical_evidence_repository import (
    StatisticalEvidenceReportRepository,
)
from empirical_platform.decision_candidate.strategy import (
    STRATEGY_ID,
    STRATEGY_VERSION,
    EvaluationMeasurements,
    EvaluationOutcome,
    EvaluationReasonCode,
    StrategyParameters,
    TradingDecision,
    evaluate,
)
from empirical_platform.decision_candidate.survivorship_study import (
    CORPORATE_ACTION_HANDLING_NOT_EXERCISED,
    HISTORICAL_MEMBERSHIP_MODEL,
    BiasStressComparison,
    CurrentUniverseBiasStressResult,
    StressWindowComparison,
    SurvivorshipAwareRobustnessStudy,
    SurvivorshipClassification,
    SurvivorshipStudyStatus,
    SurvivorshipWindowResult,
    WindowUniverseSnapshot,
    build_survivorship_aware_robustness_study,
)
from empirical_platform.decision_candidate.survivorship_study_repository import (
    SurvivorshipAwareRobustnessStudyRepository,
)
from empirical_platform.decision_candidate.trade_plan import (
    DEFAULT_RISK_POLICY,
    RISK_POLICY_ID,
    RISK_POLICY_VERSION,
    RiskPolicy,
    TradePlan,
    TradePlanGeometry,
    TradePlanRejectionReason,
    TradePlanStatus,
    build_trade_plan,
)
from empirical_platform.decision_candidate.trade_plan_repository import TradePlanRepository
from empirical_platform.decision_candidate.universe_authority import UniverseAuthority
from empirical_platform.decision_candidate.validation_study import (
    SURVIVORSHIP_BIAS_DISCLOSURE,
    HistoricalValidationStudy,
    HistoricalValidationStudyClassification,
    HistoricalValidationStudyStatus,
    ValidationDatasetBundle,
    ValidationDatasetBundleAuthority,
    ValidationSegment,
    ValidationSegmentResult,
    ValidationSegmentRole,
    ValidationSegmentSpec,
    build_validation_study,
)
from empirical_platform.decision_candidate.validation_study_repository import (
    HistoricalValidationStudyRepository,
)

__all__ = [
    "DEFAULT_RISK_POLICY",
    "DEFAULT_SIZING_POLICY",
    "SURVIVORSHIP_BIAS_DISCLOSURE",
    "REGIME_POLICY_ID",
    "REGIME_POLICY_VERSION",
    "COST_MODEL_ID",
    "COST_MODEL_VERSION",
    "DECISION_CADENCE",
    "DEFAULT_COST_MODEL",
    "DEFAULT_EXECUTION_ASSUMPTION",
    "DEFAULT_OUTCOME_MODEL",
    "EXECUTION_ASSUMPTION_ID",
    "EXECUTION_ASSUMPTION_VERSION",
    "FIXED_TEST_UNIVERSE",
    "OUTCOME_MODEL_ID",
    "OUTCOME_MODEL_VERSION",
    "RANKING_MODEL_ID",
    "RANKING_MODEL_VERSION",
    "RISK_POLICY_ID",
    "RISK_POLICY_VERSION",
    "SIZING_POLICY_ID",
    "SIZING_POLICY_VERSION",
    "STRATEGY_ID",
    "STRATEGY_VERSION",
    "Bar",
    "BarInterval",
    "DecisionCandidate",
    "DecisionCandidateRepository",
    "EvaluationMeasurements",
    "EvaluationOutcome",
    "EvaluationReasonCode",
    "HistoricalBacktestRun",
    "HistoricalBacktestRunRepository",
    "HistoricalBacktestRunStatus",
    "HistoricalCostModel",
    "HistoricalDataset",
    "HistoricalDatasetAuthority",
    "HistoricalExecutionAssumption",
    "HistoricalInstrumentSeries",
    "HistoricalOutcomeModel",
    "HistoricalTradeOutcome",
    "HistoricalValidationClassification",
    "HistoricalValidationStudy",
    "HistoricalValidationStudyClassification",
    "HistoricalValidationStudyRepository",
    "HistoricalValidationStudyStatus",
    "Instrument",
    "ObservationWindow",
    "PositionPlan",
    "PositionPlanRejectionReason",
    "PositionPlanRepository",
    "PositionPlanStatus",
    "PositionSizing",
    "PositionSizingContext",
    "RiskPolicy",
    "SameBarAmbiguityPolicy",
    "ScanEvaluationEntry",
    "SizingPolicy",
    "StrategyParameters",
    "TradePlan",
    "TradePlanGeometry",
    "TradePlanRejectionReason",
    "TradePlanRepository",
    "TradePlanStatus",
    "TradingDecision",
    "TradingOpportunityScan",
    "TradingOpportunityScanRepository",
    "ValidationDatasetBundle",
    "ValidationDatasetBundleAuthority",
    "ValidationSegment",
    "ValidationSegmentResult",
    "ValidationSegmentRole",
    "ValidationSegmentSpec",
    "HistoricalRobustnessStudy",
    "HistoricalRobustnessStudyRepository",
    "RegimeBreakdownEntry",
    "RegimeLabel",
    "RobustnessDatasetBundle",
    "RobustnessDatasetBundleAuthority",
    "RobustnessUniverseAuthority",
    "RobustnessStudyClassification",
    "RobustnessStudyStatus",
    "RobustnessWindow",
    "RobustnessWindowResult",
    "RobustnessWindowSpec",
    "WindowExtreme",
    "build_historical_backtest_run",
    "build_position_plan",
    "build_robustness_study",
    "build_scan",
    "build_trade_plan",
    "build_validation_study",
    "compute_ranking_score",
    "dataset_sha256",
    "evaluate",
    "regime_breakdown",
    "validate_scan_universe",
    "InstrumentId",
    "InstrumentMaster",
    "InstrumentMasterEntry",
    "InstrumentType",
    "FAKE_SOURCE_NAME",
    "YAHOO_FINANCE_SOURCE_NAME",
    "FakeMarketDataSource",
    "MarketDataAcquisitionError",
    "MarketDataFetchRequest",
    "MarketDataFetchResult",
    "MarketDataSource",
    "YahooFinanceChartMarketDataSource",
    "translate_fetch_result_to_pipeline_csv",
    "translate_yahoo_chart_json_to_pipeline_csv",
    "MembershipManifest",
    "MembershipRecord",
    "MembershipStatus",
    "UniverseAuthority",
    "CORPORATE_ACTION_HANDLING_NOT_EXERCISED",
    "HISTORICAL_MEMBERSHIP_MODEL",
    "BiasStressComparison",
    "CurrentUniverseBiasStressResult",
    "StressWindowComparison",
    "SurvivorshipAwareRobustnessStudy",
    "SurvivorshipAwareRobustnessStudyRepository",
    "SurvivorshipClassification",
    "SurvivorshipStudyStatus",
    "SurvivorshipWindowResult",
    "WindowUniverseSnapshot",
    "build_survivorship_aware_robustness_study",
    "canonical_membership_payload",
    "membership_manifest_hash",
    "universe_at",
    "DIVIDEND_TOTAL_RETURN_HANDLING_NOT_EXERCISED",
    "CorporateAction",
    "CorporateActionManifest",
    "CorporateActionRepository",
    "CorporateActionSemantics",
    "CorporateActionSemanticsStressRepository",
    "CorporateActionSemanticsStressResult",
    "CorporateActionType",
    "DatasetSnapshotAuthority",
    "DatasetSnapshotRepository",
    "PriceSemantics",
    "RawSourceFile",
    "SourceFileManifestEntry",
    "SplitAction",
    "StressComparison",
    "SymbolChangeAction",
    "build_corporate_action_semantics_stress",
    "corporate_action_manifest_hash",
    "dataset_snapshot_to_historical_dataset",
    "derive_split_adjusted_snapshot",
    "import_raw_historical_dataset_snapshot",
    "parse_source_csv",
    "split_adjustment_factor_at",
    "symbol_at",
    "volume_adjustment_factor_at",
    "write_dataset_artifact",
    "DEFAULT_BOOTSTRAP_POLICY",
    "FALSE_CONFIDENCE_FIREWALL_LIMITATIONS",
    "MINIMUM_RESAMPLE_COUNT",
    "SUPPORTED_CONFIDENCE_LEVELS",
    "BootstrapInterval",
    "BootstrapMethod",
    "BootstrapPolicy",
    "DrawdownPathEvidence",
    "SampleUnit",
    "SensitivityLabel",
    "SensitivityView",
    "StatisticalEvidenceClassification",
    "StatisticalEvidenceReport",
    "StatisticalEvidenceReportRepository",
    "build_statistical_evidence_report",
    "DEFAULT_PORTFOLIO_CAPITAL_POLICY",
    "CapitalSensitivityLabel",
    "CapitalSensitivityView",
    "PortfolioAllocationDecision",
    "PortfolioAllocationOutcome",
    "PortfolioCapitalPolicy",
    "PortfolioEquityObservation",
    "PortfolioEventKind",
    "PortfolioEvidenceReport",
    "PortfolioRejectionReason",
    "PortfolioStudyRepository",
    "build_portfolio_evidence_report",
    "DEFAULT_DEPENDENCE_ESTIMATION_POLICY",
    "FALSE_DIVERSIFICATION_FIREWALL_LIMITATIONS",
    "ConcentrationStressResult",
    "ConcurrentExposureState",
    "DependenceEstimationPolicy",
    "DependenceEvidenceClassification",
    "PairDependenceStatus",
    "PairwiseDependenceEvidence",
    "PortfolioDependenceReport",
    "PortfolioDependenceReportRepository",
    "build_pairwise_dependence",
    "build_concurrent_exposure_states",
    "build_portfolio_dependence_report",
]
