"""Generate the M084 file-audit matrix from the real diff and the real files.

    python tools/render_m084_file_audit.py            # write the matrix
    python tools/render_m084_file_audit.py --check    # fail if it has drifted

Nothing here is hand-maintained. The path set comes from `git diff`, the line
counts and public surfaces come from reading the files themselves, and the
purpose column comes from a table in this file that must name every path -- an
unnamed path renders as an error rather than a blank cell, so a file added
without being audited fails the render instead of appearing unexplained.

`--check` is the gate. A matrix that had to be regenerated by hand after every
commit would be stale exactly when it mattered.
"""

from __future__ import annotations

import argparse
import ast
import json
import subprocess
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
PACKAGE = REPO_ROOT / "external-review" / "MILESTONE-084"
MATRIX_JSON = PACKAGE / "file-audit-matrix.json"
MATRIX_MARKDOWN = PACKAGE / "file-audit-matrix.md"
BASE = "707161a1e8edeb7e0c95f3dafc7180ba9d782cc6"

_OWNERSHIP = {
    "external-review/": "M084 review package",
    "migrations/": "M084 schema",
    "src/empirical_platform/decision_candidate/": "M084 domain",
    "src/empirical_platform/entrypoints/": "M084 operator CLI",
    "src/empirical_platform/shared/persistence/": "M084 persistence",
    "src/empirical_platform/usecases/": "M084 application",
    "tests/architecture/": "shared architecture gate",
    "tests/fixtures/": "shared negative fixtures",
    "tests/integration/": "M084 tests",
    "tests/unit/": "M084 tests",
    "tools/": "shared toolchain",
    "pyproject.toml": "shared packaging",
}

_PURPOSE = {
    "external-review/MILESTONE-084/README.md": "Package entry point and reading order",
    "external-review/MILESTONE-084/broker-and-market-data-research.md": (
        "Phase C research; states its own source limitation before any claim"
    ),
    "external-review/MILESTONE-084/changed-files.txt": "The exact diff surface",
    "external-review/MILESTONE-084/concurrency-results.md": (
        "Executed concurrency races, three clean schema repetitions"
    ),
    "external-review/MILESTONE-084/current-authority.json": (
        "The canonical authority contract; the only source of M084 authority"
    ),
    "external-review/MILESTONE-084/current-authority.md": (
        "Deterministic rendering of the contract; never hand-edited"
    ),
    "external-review/MILESTONE-084/current-authority.schema.json": (
        "Closed schema; exact item counts make adding and dropping equally visible"
    ),
    "external-review/MILESTONE-084/exhaustion-table.md": (
        "One machine-checked row per required campaign item"
    ),
    "external-review/MILESTONE-084/file-audit-matrix.json": (
        "This matrix, machine-checked against the diff and the filesystem"
    ),
    "external-review/MILESTONE-084/file-audit-matrix.md": "This matrix, rendered",
    "external-review/MILESTONE-084/hostile-review.md": (
        "Five formally separate hostile passes, each with its own conclusion"
    ),
    "external-review/MILESTONE-084/mutation-matrix.md": (
        "All 27 mutation families: mutated, detected, restored, re-verified"
    ),
    "external-review/MILESTONE-084/operator-verification-checklist.md": (
        "Exact URLs and questions for facts this environment could not verify"
    ),
    "external-review/MILESTONE-084/performance-results.md": (
        "Measured latency and scale, with the environment boundary stated"
    ),
    "external-review/MILESTONE-084/scope-and-design.md": (
        "What was built and why each refusal sits where it does"
    ),
    "external-review/MILESTONE-084/validation-results.md": (
        "What was executed and measured; what was not is listed, not omitted"
    ),
    "migrations/versions/a3f7c21d9b04_create_m084_decision_to_approval_schema.py": (
        "Six tables: the four hard invariants, the closed state machine, the append-only guards"
    ),
    "pyproject.toml": "Registers the M084 operator console scripts",
    "src/empirical_platform/decision_candidate/evaluation_context.py": (
        "Binds one evaluation to the M083 watermark it consumed"
    ),
    "src/empirical_platform/decision_candidate/operator_trading_configuration.py": (
        "Versioned operator policy; refuses a policy this product will not hold"
    ),
    "src/empirical_platform/decision_candidate/product_market_inputs.py": (
        "Provider-neutral, operator-asserted observations"
    ),
    "src/empirical_platform/decision_candidate/product_repositories.py": (
        "Persistence-neutral contracts; no update, no delete, no submit"
    ),
    "src/empirical_platform/decision_candidate/trade_approval.py": (
        "Closed transition table, human decision, never-submitted intent"
    ),
    "src/empirical_platform/decision_candidate/trade_proposal.py": (
        "Deterministic engine; the caller supplies no quantity, price or verdict"
    ),
    (
        "src/empirical_platform/shared/persistence/postgres_repositories/"
        "decision_to_approval_repositories.py"
    ): "Five repositories; reads fail closed rather than coerce",
    "src/empirical_platform/shared/persistence/postgres_repositories/runtime.py": (
        "Registers the five M084 repositories on the shared runtime"
    ),
    "src/empirical_platform/usecases/decision_to_approval.py": (
        "Commands and queries; one step each, nothing spans the human decision"
    ),
    "src/empirical_platform/usecases/decision_to_approval_io.py": (
        "Reads operator input refusing rather than repairing; renders results"
    ),
    "tests/architecture/test_module_boundaries.py": ("Adds the order-submission boundary tests"),
    "tools/check_architecture.py": "Adds the package-wide order-submission deny-list",
    "tools/render_m084_authority.py": "Deterministic authority renderer with --check",
    "tools/render_m084_file_audit.py": "This generator",
}

_ENTRYPOINT_PURPOSE = {
    "audit_history": "Operator CLI: the whole chain behind one proposal",
    "decide_trade_proposal": "Operator CLI: the one command a human must run",
    "explain_no_trade": "Operator CLI: every check, not only the reported reason",
    "get_order_intent": "Operator CLI: read one never-submitted intent",
    "get_trade_proposal": "Operator CLI: read one proposal and its terms",
    "invalidate_stale_proposals": "Operator CLI: sweep the PREPARED queue",
    "issue_order_intent": "Operator CLI: derive the one intent an approval permits",
    "kill_switch": "Operator CLI: the global stop (status, on, off)",
    "list_trade_proposals": "Operator CLI: the queue awaiting a decision",
    "open_evaluation_context": "Operator CLI: bind an evaluation to its inputs",
    "prepare_trade_proposal": "Operator CLI: evaluate one instrument",
    "save_trading_configuration": "Operator CLI: store one policy version",
    "show_trading_configuration": "Operator CLI: read a stored policy version",
    "system_status": "Operator CLI: queue, policy, and what the product cannot do",
    "validate_trading_configuration": "Operator CLI: check a file, touching no database",
}


class AuditError(RuntimeError):
    """A path the matrix cannot describe."""


def _ownership(path: str) -> str:
    for prefix, owner in _OWNERSHIP.items():
        if path.startswith(prefix):
            return owner
    raise AuditError(f"no ownership rule covers {path!r}")


def _purpose(path: str) -> str:
    if path in _PURPOSE:
        return _PURPOSE[path]
    if path.startswith("src/empirical_platform/entrypoints/"):
        stem = Path(path).stem
        if stem in _ENTRYPOINT_PURPOSE:
            return _ENTRYPOINT_PURPOSE[stem]
        raise AuditError(f"entrypoint {stem!r} has no purpose entry")
    if "illegal_imports" in path:
        return "Negative fixture: proves the order-submission deny-list fires"
    if path.startswith("tests/"):
        return "Test suite"
    raise AuditError(f"no purpose entry for {path!r}")


def _surface(path: str) -> str:
    """The module's declared `__all__`, else its public names."""
    if not path.endswith(".py"):
        return "-"
    tree = ast.parse((REPO_ROOT / path).read_text(encoding="utf-8"))
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(
            isinstance(target, ast.Name) and target.id == "__all__" for target in node.targets
        ):
            elements = node.value
            if isinstance(elements, ast.List):
                return ", ".join(
                    sorted(
                        element.value
                        for element in elements.elts
                        if isinstance(element, ast.Constant)
                    )
                )
    names = [
        node.name
        for node in tree.body
        if isinstance(node, ast.ClassDef | ast.FunctionDef) and not node.name.startswith("_")
    ]
    return ", ".join(names) if names else "(module-private)"


def build() -> dict[str, Any]:
    result = subprocess.run(  # noqa: S603 - fixed argument vector, no shell
        ["git", "diff", "--name-status", f"{BASE}..HEAD"],  # noqa: S607
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    status = {}
    for line in result.stdout.splitlines():
        code, path = line.split("\t", 1)
        status[path] = {"A": "new", "M": "modified", "D": "deleted"}[code[0]]

    rows = []
    for number, path in enumerate(sorted(status), start=1):
        rows.append(
            {
                "n": number,
                "path": path,
                "status": status[path],
                "ownership": _ownership(path),
                "lines": len((REPO_ROOT / path).read_text(encoding="utf-8").splitlines()),
                "surface": _surface(path),
            }
        )
    return {"base": BASE, "count": len(rows), "files": rows}


def render_markdown(matrix: dict[str, Any]) -> str:
    lines = [
        "# MILESTONE-084 — File Audit Matrix",
        "",
        f"Base `{matrix['base'][:12]}` .. HEAD. **{matrix['count']} paths.**",
        "",
        "Generated by `tools/render_m084_file_audit.py`; do not edit by hand. The path",
        "set comes from `git diff`, the line counts and public surfaces from reading the",
        "files, and every path must have an explicit purpose entry -- a file added",
        "without being audited fails the render rather than appearing as a blank cell.",
        "",
        "`tests/integration/test_m084_file_audit.py` checks this matrix against the real",
        "diff, against `changed-files.txt`, and against the filesystem.",
        "",
        "| # | Path | Status | Ownership | Purpose | Lines | Public surface |",
        "|---|---|---|---|---|---|---|",
    ]
    for row in matrix["files"]:
        surface = row["surface"]
        if len(surface) > 110:
            surface = surface[:107] + "..."
        lines.append(
            f"| {row['n']} | `{row['path']}` | {row['status']} | {row['ownership']} | "
            f"{_purpose(row['path'])} | {row['lines']} | {surface} |"
        )
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the matrix has drifted")
    args = parser.parse_args(argv)

    matrix = build()
    expected_json = json.dumps(matrix, indent=2) + "\n"
    expected_markdown = render_markdown(matrix)

    if args.check:
        actual_json = MATRIX_JSON.read_text(encoding="utf-8") if MATRIX_JSON.exists() else ""
        actual_markdown = (
            MATRIX_MARKDOWN.read_text(encoding="utf-8") if MATRIX_MARKDOWN.exists() else ""
        )
        if actual_json != expected_json or actual_markdown != expected_markdown:
            print(
                "the file-audit matrix is not the current rendering of the diff",
                file=sys.stderr,
            )
            return 1
        print(f"file-audit matrix matches the diff ({matrix['count']} paths)")
        return 0

    MATRIX_JSON.write_text(expected_json, encoding="utf-8")
    MATRIX_MARKDOWN.write_text(expected_markdown, encoding="utf-8")
    print(f"wrote the file-audit matrix ({matrix['count']} paths)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
